name: Publish Docker Images to GitHub Container Registry

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  IMAGE1_NAME: ghcr.io/rishikesavanramesh/skypod/image1
  IMAGE2_NAME: ghcr.io/rishikesavanramesh/skypod/image2
  IMAGE3_NAME: ghcr.io/rishikesavanramesh/skypod/image3

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_PAT }}

    - name: Build and push image1
      uses: docker/build-push-action@v2
      with:
        context: ./image1
        push: true
        tags: ${{ env.IMAGE1_NAME }}:${{ github.sha }}

    - name: Build and push image2
      uses: docker/build-push-action@v2
      with:
        context: ./image2
        push: true
        tags: ${{ env.IMAGE2_NAME }}:${{ github.sha }}

    - name: Build and push image3
      uses: docker/build-push-action@v2
      with:
        context: ./image3
        push: true
        tags: ${{ env.IMAGE3_NAME }}:${{ github.sha }}
